# Generated by Django 6.0.5 on 2026-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invitetoken_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_36d76d_idx',
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin')], default='admin', max_length=10, verbose_name='Rol'),
        ),
    ]
