# Generated by Django 6.0.5 on 2026-06-08 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Yechim fayli')),
                ('answer_text', models.TextField(blank=True, verbose_name='Yozma javob')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Baholash (Ball)')),
                ('teacher_comment', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=10, verbose_name='Holati')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_assignments.assignment', verbose_name='Vazifa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Topshiriq yechimi',
                'verbose_name_plural': 'Topshiriq yechimlari',
            },
        ),
    ]
