# Generated by Django 6.0.5 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('B', 'Bajarilmagan'), ('K', 'Kutilmoqda'), ('Q', 'Qabul qilindi'), ('R', 'Rad etildi')], default='B', max_length=10, verbose_name='Holati'),
        ),
    ]
